# Enable stateless CSRF protection for forms and logins/logouts

framework:
    csrf_protection:
        enabled: true

    form:
        csrf_protection:
            enabled: true
            token_id: submit
