framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'no-reply@stay-platform.local'
        headers:
            From: 'Plateforme de réservation <no-reply@stay-platform.local>'
