framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # Route email sending asynchronously
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            # Route our reservation messages asynchronously
            App\Message\ReservationConfirmedMessage: async
