FROM php:8.4-fpm-alpine

RUN sed -i 's|https://|http://|g' /etc/apk/repositories

RUN apk add --no-cache \
    postgresql-dev \
    git \
    unzip \
    curl \
    libpng-dev \
    libzip-dev \
    oniguruma-dev \
    icu-dev \
    rabbitmq-c-dev

RUN docker-php-ext-install \
    pdo \
    pdo_pgsql \
    opcache \
    gd \
    zip \
    mbstring \
    intl

RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
    && curl -fsSL -o /tmp/apcu.tgz  http://pecl.php.net/get/apcu \
    && curl -fsSL -o /tmp/redis.tgz http://pecl.php.net/get/redis \
    && curl -fsSL -o /tmp/amqp.tgz  http://pecl.php.net/get/amqp \
    && pecl install /tmp/apcu.tgz /tmp/redis.tgz /tmp/amqp.tgz \
    && docker-php-ext-enable apcu redis amqp \
    && rm -f /tmp/*.tgz \
    && apk del .build-deps

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

RUN chown -R www-data:www-data /var/www/html
