<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260611190500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Aligne la cle primaire realtime_events avec la strategie identity de Doctrine.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE realtime_events ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE realtime_events ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE realtime_events ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql("CREATE SEQUENCE realtime_events_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("SELECT setval('realtime_events_id_seq', COALESCE((SELECT MAX(id) FROM realtime_events), 1), true)");
        $this->addSql("ALTER TABLE realtime_events ALTER id SET DEFAULT nextval('realtime_events_id_seq')");
        $this->addSql('ALTER SEQUENCE realtime_events_id_seq OWNED BY realtime_events.id');
    }
}
