<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260610153000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remplace les tables roles/user_roles par une colonne JSON roles sur users';
    }

    public function up(Schema $schema): void
    {
        if (!$schema->getTable('users')->hasColumn('roles')) {
            $this->addSql('ALTER TABLE users ADD roles JSON NOT NULL DEFAULT \'[]\'');
        }

        if ($schema->hasTable('user_roles') && $schema->hasTable('roles')) {
            $this->addSql(<<<'SQL'
                UPDATE users u
                SET roles = COALESCE(
                    (
                        SELECT json_agg(r.code ORDER BY r.code)
                        FROM user_roles ur
                        INNER JOIN roles r ON r.id = ur.role_id
                        WHERE ur.user_id = u.id
                    ),
                    '[]'::json
                )
                SQL);
            $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FA76ED395');
            $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FD60322AC');
            $this->addSql('DROP TABLE user_roles');
            $this->addSql('DROP TABLE roles');
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS roles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_B63E2EC777153098 ON roles (code)');
        $this->addSql('CREATE TABLE IF NOT EXISTS user_roles (user_id UUID NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_54FCD59FA76ED395 ON user_roles (user_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_54FCD59FD60322AC ON user_roles (role_id)');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FD60322AC FOREIGN KEY (role_id) REFERENCES roles (id) NOT DEFERRABLE');

        $this->addSql("INSERT INTO roles (code, label) VALUES ('ROLE_HOST', 'Hôte'), ('ROLE_ADMIN', 'Administrateur'), ('ROLE_SUPER_ADMIN', 'Super Administrateur')");

        $this->addSql(<<<'SQL'
            INSERT INTO user_roles (user_id, role_id)
            SELECT u.id, r.id
            FROM users u
            CROSS JOIN LATERAL json_array_elements_text(u.roles) AS role_code(value)
            INNER JOIN roles r ON r.code = role_code.value
            SQL);

        $this->addSql('ALTER TABLE users DROP roles');
    }
}
