<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260608080710 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Init DB';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE amenities (code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, category VARCHAR(50) DEFAULT NULL, id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB70547777153098 ON amenities (code)');
        $this->addSql('CREATE TABLE audit_logs (action VARCHAR(100) NOT NULL, entity_type VARCHAR(100) NOT NULL, entity UUID NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, user_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D62F2858A76ED395 ON audit_logs (user_id)');
        $this->addSql('CREATE TABLE cancellation_policies (code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_52BE2A177153098 ON cancellation_policies (code)');
        $this->addSql('CREATE TABLE conversation_participants (conversation_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (conversation_id, user_id))');
        $this->addSql('CREATE INDEX IDX_21821ED39AC0396 ON conversation_participants (conversation_id)');
        $this->addSql('CREATE INDEX IDX_21821ED3A76ED395 ON conversation_participants (user_id)');
        $this->addSql('CREATE TABLE conversations (created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reservation_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C2521BF1B83297E7 ON conversations (reservation_id)');
        $this->addSql('CREATE TABLE disputes (status VARCHAR(50) NOT NULL, resolution TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reservation_id UUID NOT NULL, opened_by_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8556C8F8B83297E7 ON disputes (reservation_id)');
        $this->addSql('CREATE INDEX IDX_8556C8F8AB159F5 ON disputes (opened_by_id)');
        $this->addSql('CREATE TABLE invoices (invoice_number VARCHAR(50) NOT NULL, pdf_url TEXT DEFAULT NULL, total_amount NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reservation_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A2F2F952DA68207 ON invoices (invoice_number)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A2F2F95B83297E7 ON invoices (reservation_id)');
        $this->addSql('CREATE TABLE messages (message_type VARCHAR(50) NOT NULL, content TEXT DEFAULT NULL, attachment_url TEXT DEFAULT NULL, is_flagged BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, conversation_id UUID NOT NULL, sender_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB021E969AC0396 ON messages (conversation_id)');
        $this->addSql('CREATE INDEX IDX_DB021E96F624B39D ON messages (sender_id)');
        $this->addSql('CREATE TABLE notifications (type VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, channel VARCHAR(50) NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('CREATE TABLE oauth_accounts (provider VARCHAR(50) NOT NULL, provider_user_id VARCHAR(255) NOT NULL, access_token TEXT DEFAULT NULL, refresh_token TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EAB41DB0A76ED395 ON oauth_accounts (user_id)');
        $this->addSql('CREATE TABLE payment_methods (provider VARCHAR(50) NOT NULL, provider_payment_method_id VARCHAR(255) NOT NULL, brand VARCHAR(50) DEFAULT NULL, last4 VARCHAR(4) DEFAULT NULL, expiration_month INT DEFAULT NULL, expiration_year INT DEFAULT NULL, id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4FABF983A76ED395 ON payment_methods (user_id)');
        $this->addSql('CREATE TABLE payments (provider VARCHAR(50) NOT NULL, provider_payment_intent VARCHAR(255) NOT NULL, amount NUMERIC(10, 2) NOT NULL, currency VARCHAR(10) NOT NULL, status VARCHAR(50) NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reservation_id UUID NOT NULL, payer_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65D29B32B83297E7 ON payments (reservation_id)');
        $this->addSql('CREATE INDEX IDX_65D29B32C17AD9A9 ON payments (payer_id)');
        $this->addSql('CREATE TABLE payouts (amount NUMERIC(10, 2) NOT NULL, currency VARCHAR(10) NOT NULL, status VARCHAR(50) NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id UUID NOT NULL, host_id UUID NOT NULL, reservation_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F54E808E1FB8D185 ON payouts (host_id)');
        $this->addSql('CREATE INDEX IDX_F54E808EB83297E7 ON payouts (reservation_id)');
        $this->addSql('CREATE TABLE properties (title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, property_type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, max_guests INT NOT NULL, bedrooms INT NOT NULL, beds INT NOT NULL, bathrooms INT NOT NULL, price_per_night NUMERIC(10, 2) NOT NULL, cleaning_fee NUMERIC(10, 2) DEFAULT NULL, security_deposit NUMERIC(10, 2) DEFAULT NULL, checkin_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, checkout_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, instant_booking BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id UUID NOT NULL, host_id UUID NOT NULL, cancellation_policy_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_87C331C71FB8D185 ON properties (host_id)');
        $this->addSql('CREATE INDEX IDX_87C331C7F0C13F52 ON properties (cancellation_policy_id)');
        $this->addSql('CREATE TABLE property_addresses (country VARCHAR(100) NOT NULL, city VARCHAR(100) NOT NULL, postal_code VARCHAR(20) DEFAULT NULL, address_line1 VARCHAR(255) NOT NULL, address_line2 VARCHAR(255) DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, id UUID NOT NULL, property_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E2577AB549213EC ON property_addresses (property_id)');
        $this->addSql('CREATE TABLE property_amenities (property_id UUID NOT NULL, amenity_id UUID NOT NULL, PRIMARY KEY (property_id, amenity_id))');
        $this->addSql('CREATE INDEX IDX_9A9F56CA549213EC ON property_amenities (property_id)');
        $this->addSql('CREATE INDEX IDX_9A9F56CA9F9F1305 ON property_amenities (amenity_id)');
        $this->addSql('CREATE TABLE property_availability (available_date DATE NOT NULL, is_available BOOLEAN NOT NULL, price_override NUMERIC(10, 2) DEFAULT NULL, minimum_stay INT DEFAULT NULL, id UUID NOT NULL, property_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F0B252E6549213EC ON property_availability (property_id)');
        $this->addSql('CREATE TABLE property_ical_sync (provider_name VARCHAR(100) NOT NULL, i_cal_url TEXT NOT NULL, last_sync_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id UUID NOT NULL, property_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DC997CB8549213EC ON property_ical_sync (property_id)');
        $this->addSql('CREATE TABLE property_media (media_type VARCHAR(50) NOT NULL, file_url TEXT NOT NULL, sort_order INT NOT NULL, is_cover BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, property_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC3F6001549213EC ON property_media (property_id)');
        $this->addSql('CREATE TABLE property_rules (pets_allowed BOOLEAN NOT NULL, smoking_allowed BOOLEAN NOT NULL, parties_allowed BOOLEAN NOT NULL, additional_rules TEXT DEFAULT NULL, id UUID NOT NULL, property_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4F895831549213EC ON property_rules (property_id)');
        $this->addSql('CREATE TABLE refunds (amount NUMERIC(10, 2) NOT NULL, reason TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, payment_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7EE53AD94C3A3BB ON refunds (payment_id)');
        $this->addSql('CREATE TABLE reports (target_type VARCHAR(50) NOT NULL, target UUID NOT NULL, reason TEXT NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reporter_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F11FA745E1CFE6F5 ON reports (reporter_id)');
        $this->addSql('CREATE TABLE reservation_status_history (old_status VARCHAR(50) DEFAULT NULL, new_status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reservation_id UUID NOT NULL, changed_by_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3A5E46F7B83297E7 ON reservation_status_history (reservation_id)');
        $this->addSql('CREATE INDEX IDX_3A5E46F7828AD0A0 ON reservation_status_history (changed_by_id)');
        $this->addSql('CREATE TABLE booking (checkin_date DATE NOT NULL, checkout_date DATE NOT NULL, guests_count INT NOT NULL, status VARCHAR(50) NOT NULL, total_price NUMERIC(10, 2) NOT NULL, cleaning_fee NUMERIC(10, 2) DEFAULT NULL, service_fee NUMERIC(10, 2) DEFAULT NULL, security_deposit NUMERIC(10, 2) DEFAULT NULL, currency VARCHAR(10) NOT NULL, cancellation_reason TEXT DEFAULT NULL, cancelled_by VARCHAR(10) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, property_id UUID NOT NULL, guest_id UUID NOT NULL, host_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_booking_property_status ON booking (property_id, status)');
        $this->addSql('CREATE INDEX idx_booking_dates ON booking (checkin_date, checkout_date)');
        $this->addSql('CREATE INDEX IDX_E00CEDDE549213EC ON booking (property_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDE9A4AA658 ON booking (guest_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDE1FB8D185 ON booking (host_id)');
        $this->addSql('CREATE TABLE review_media (file_url TEXT NOT NULL, id UUID NOT NULL, review_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_79A28D173E2E969B ON review_media (review_id)');
        $this->addSql('CREATE TABLE review_reports (reason TEXT NOT NULL, status VARCHAR(50) NOT NULL, id UUID NOT NULL, review_id UUID NOT NULL, reported_by_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6AF113B23E2E969B ON review_reports (review_id)');
        $this->addSql('CREATE INDEX IDX_6AF113B271CE806 ON review_reports (reported_by_id)');
        $this->addSql('CREATE TABLE reviews (rating INT NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reservation_id UUID NOT NULL, reviewer_id UUID NOT NULL, reviewed_user_id UUID NOT NULL, property_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6970EB0FB83297E7 ON reviews (reservation_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0F70574616 ON reviews (reviewer_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0FB9A2A077 ON reviews (reviewed_user_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0F549213EC ON reviews (property_id)');
        $this->addSql('CREATE TABLE roles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B63E2EC777153098 ON roles (code)');
        $this->addSql('CREATE TABLE user_documents (type VARCHAR(50) NOT NULL, file_url TEXT NOT NULL, verification_status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A250FF6CA76ED395 ON user_documents (user_id)');
        $this->addSql('CREATE TABLE user_profiles (first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, birth_date DATE DEFAULT NULL, avatar_url TEXT DEFAULT NULL, bio TEXT DEFAULT NULL, identity_status VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6BBD6130A76ED395 ON user_profiles (user_id)');
        $this->addSql('CREATE TABLE user_roles (user_id UUID NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_54FCD59FA76ED395 ON user_roles (user_id)');
        $this->addSql('CREATE INDEX IDX_54FCD59FD60322AC ON user_roles (role_id)');
        $this->addSql('CREATE TABLE users (email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, phone VARCHAR(50) DEFAULT NULL, status VARCHAR(50) NOT NULL, is_email_verified BOOLEAN NOT NULL, is2fa_enabled BOOLEAN NOT NULL, preferred_language VARCHAR(10) DEFAULT NULL, preferred_currency VARCHAR(10) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_D62F2858A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation_participants ADD CONSTRAINT FK_21821ED39AC0396 FOREIGN KEY (conversation_id) REFERENCES conversations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation_participants ADD CONSTRAINT FK_21821ED3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversations ADD CONSTRAINT FK_C2521BF1B83297E7 FOREIGN KEY (reservation_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE disputes ADD CONSTRAINT FK_8556C8F8B83297E7 FOREIGN KEY (reservation_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE disputes ADD CONSTRAINT FK_8556C8F8AB159F5 FOREIGN KEY (opened_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoices ADD CONSTRAINT FK_6A2F2F95B83297E7 FOREIGN KEY (reservation_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E969AC0396 FOREIGN KEY (conversation_id) REFERENCES conversations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96F624B39D FOREIGN KEY (sender_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE oauth_accounts ADD CONSTRAINT FK_EAB41DB0A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment_methods ADD CONSTRAINT FK_4FABF983A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B32B83297E7 FOREIGN KEY (reservation_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B32C17AD9A9 FOREIGN KEY (payer_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payouts ADD CONSTRAINT FK_F54E808E1FB8D185 FOREIGN KEY (host_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payouts ADD CONSTRAINT FK_F54E808EB83297E7 FOREIGN KEY (reservation_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE properties ADD CONSTRAINT FK_87C331C71FB8D185 FOREIGN KEY (host_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE properties ADD CONSTRAINT FK_87C331C7F0C13F52 FOREIGN KEY (cancellation_policy_id) REFERENCES cancellation_policies (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_addresses ADD CONSTRAINT FK_1E2577AB549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_amenities ADD CONSTRAINT FK_9A9F56CA549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_amenities ADD CONSTRAINT FK_9A9F56CA9F9F1305 FOREIGN KEY (amenity_id) REFERENCES amenities (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_availability ADD CONSTRAINT FK_F0B252E6549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_ical_sync ADD CONSTRAINT FK_DC997CB8549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_media ADD CONSTRAINT FK_AC3F6001549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_rules ADD CONSTRAINT FK_4F895831549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE refunds ADD CONSTRAINT FK_7EE53AD94C3A3BB FOREIGN KEY (payment_id) REFERENCES payments (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT FK_F11FA745E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation_status_history ADD CONSTRAINT FK_3A5E46F7B83297E7 FOREIGN KEY (reservation_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation_status_history ADD CONSTRAINT FK_3A5E46F7828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE9A4AA658 FOREIGN KEY (guest_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE1FB8D185 FOREIGN KEY (host_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review_media ADD CONSTRAINT FK_79A28D173E2E969B FOREIGN KEY (review_id) REFERENCES reviews (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review_reports ADD CONSTRAINT FK_6AF113B23E2E969B FOREIGN KEY (review_id) REFERENCES reviews (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review_reports ADD CONSTRAINT FK_6AF113B271CE806 FOREIGN KEY (reported_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FB83297E7 FOREIGN KEY (reservation_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0F70574616 FOREIGN KEY (reviewer_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FB9A2A077 FOREIGN KEY (reviewed_user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0F549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_documents ADD CONSTRAINT FK_A250FF6CA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_profiles ADD CONSTRAINT FK_6BBD6130A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FD60322AC FOREIGN KEY (role_id) REFERENCES roles (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT FK_D62F2858A76ED395');
        $this->addSql('ALTER TABLE conversation_participants DROP CONSTRAINT FK_21821ED39AC0396');
        $this->addSql('ALTER TABLE conversation_participants DROP CONSTRAINT FK_21821ED3A76ED395');
        $this->addSql('ALTER TABLE conversations DROP CONSTRAINT FK_C2521BF1B83297E7');
        $this->addSql('ALTER TABLE disputes DROP CONSTRAINT FK_8556C8F8B83297E7');
        $this->addSql('ALTER TABLE disputes DROP CONSTRAINT FK_8556C8F8AB159F5');
        $this->addSql('ALTER TABLE invoices DROP CONSTRAINT FK_6A2F2F95B83297E7');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E969AC0396');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96F624B39D');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE oauth_accounts DROP CONSTRAINT FK_EAB41DB0A76ED395');
        $this->addSql('ALTER TABLE payment_methods DROP CONSTRAINT FK_4FABF983A76ED395');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B32B83297E7');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B32C17AD9A9');
        $this->addSql('ALTER TABLE payouts DROP CONSTRAINT FK_F54E808E1FB8D185');
        $this->addSql('ALTER TABLE payouts DROP CONSTRAINT FK_F54E808EB83297E7');
        $this->addSql('ALTER TABLE properties DROP CONSTRAINT FK_87C331C71FB8D185');
        $this->addSql('ALTER TABLE properties DROP CONSTRAINT FK_87C331C7F0C13F52');
        $this->addSql('ALTER TABLE property_addresses DROP CONSTRAINT FK_1E2577AB549213EC');
        $this->addSql('ALTER TABLE property_amenities DROP CONSTRAINT FK_9A9F56CA549213EC');
        $this->addSql('ALTER TABLE property_amenities DROP CONSTRAINT FK_9A9F56CA9F9F1305');
        $this->addSql('ALTER TABLE property_availability DROP CONSTRAINT FK_F0B252E6549213EC');
        $this->addSql('ALTER TABLE property_ical_sync DROP CONSTRAINT FK_DC997CB8549213EC');
        $this->addSql('ALTER TABLE property_media DROP CONSTRAINT FK_AC3F6001549213EC');
        $this->addSql('ALTER TABLE property_rules DROP CONSTRAINT FK_4F895831549213EC');
        $this->addSql('ALTER TABLE refunds DROP CONSTRAINT FK_7EE53AD94C3A3BB');
        $this->addSql('ALTER TABLE reports DROP CONSTRAINT FK_F11FA745E1CFE6F5');
        $this->addSql('ALTER TABLE reservation_status_history DROP CONSTRAINT FK_3A5E46F7B83297E7');
        $this->addSql('ALTER TABLE reservation_status_history DROP CONSTRAINT FK_3A5E46F7828AD0A0');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE549213EC');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE9A4AA658');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE1FB8D185');
        $this->addSql('ALTER TABLE review_media DROP CONSTRAINT FK_79A28D173E2E969B');
        $this->addSql('ALTER TABLE review_reports DROP CONSTRAINT FK_6AF113B23E2E969B');
        $this->addSql('ALTER TABLE review_reports DROP CONSTRAINT FK_6AF113B271CE806');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0FB83297E7');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0F70574616');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0FB9A2A077');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0F549213EC');
        $this->addSql('ALTER TABLE user_documents DROP CONSTRAINT FK_A250FF6CA76ED395');
        $this->addSql('ALTER TABLE user_profiles DROP CONSTRAINT FK_6BBD6130A76ED395');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FA76ED395');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FD60322AC');
        $this->addSql('DROP TABLE amenities');
        $this->addSql('DROP TABLE audit_logs');
        $this->addSql('DROP TABLE cancellation_policies');
        $this->addSql('DROP TABLE conversation_participants');
        $this->addSql('DROP TABLE conversations');
        $this->addSql('DROP TABLE disputes');
        $this->addSql('DROP TABLE invoices');
        $this->addSql('DROP TABLE messages');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE oauth_accounts');
        $this->addSql('DROP TABLE payment_methods');
        $this->addSql('DROP TABLE payments');
        $this->addSql('DROP TABLE payouts');
        $this->addSql('DROP TABLE properties');
        $this->addSql('DROP TABLE property_addresses');
        $this->addSql('DROP TABLE property_amenities');
        $this->addSql('DROP TABLE property_availability');
        $this->addSql('DROP TABLE property_ical_sync');
        $this->addSql('DROP TABLE property_media');
        $this->addSql('DROP TABLE property_rules');
        $this->addSql('DROP TABLE refunds');
        $this->addSql('DROP TABLE reports');
        $this->addSql('DROP TABLE reservation_status_history');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE review_media');
        $this->addSql('DROP TABLE review_reports');
        $this->addSql('DROP TABLE reviews');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE user_documents');
        $this->addSql('DROP TABLE user_profiles');
        $this->addSql('DROP TABLE user_roles');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
