<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;


final class Version20260608084501 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'caca';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE amenities (code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, category VARCHAR(50) DEFAULT NULL, id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB70547777153098 ON amenities (code)');
        $this->addSql('CREATE TABLE audit_logs (action VARCHAR(100) NOT NULL, entity_type VARCHAR(100) NOT NULL, entity UUID NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, user_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D62F2858A76ED395 ON audit_logs (user_id)');
        $this->addSql('CREATE TABLE cancellation_policies (code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_52BE2A177153098 ON cancellation_policies (code)');
        $this->addSql('CREATE TABLE conversation_participants (conversation_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (conversation_id, user_id))');
        $this->addSql('CREATE INDEX IDX_21821ED39AC0396 ON conversation_participants (conversation_id)');
        $this->addSql('CREATE INDEX IDX_21821ED3A76ED395 ON conversation_participants (user_id)');
        $this->addSql('CREATE TABLE conversations (created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reservation_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C2521BF1B83297E7 ON conversations (reservation_id)');
        $this->addSql('CREATE TABLE disputes (status VARCHAR(50) NOT NULL, resolution TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reservation_id UUID NOT NULL, opened_by_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8556C8F8B83297E7 ON disputes (reservation_id)');
        $this->addSql('CREATE INDEX IDX_8556C8F8AB159F5 ON disputes (opened_by_id)');
        $this->addSql('CREATE TABLE invoices (invoice_number VARCHAR(50) NOT NULL, pdf_url TEXT DEFAULT NULL, total_amount NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reservation_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A2F2F952DA68207 ON invoices (invoice_number)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A2F2F95B83297E7 ON invoices (reservation_id)');
        $this->addSql('CREATE TABLE messages (message_type VARCHAR(50) NOT NULL, content TEXT DEFAULT NULL, attachment_url TEXT DEFAULT NULL, is_flagged BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, conversation_id UUID NOT NULL, sender_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB021E969AC0396 ON messages (conversation_id)');
        $this->addSql('CREATE INDEX IDX_DB021E96F624B39D ON messages (sender_id)');
        $this->addSql('CREATE TABLE notifications (type VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, channel VARCHAR(50) NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('CREATE TABLE oauth_accounts (provider VARCHAR(50) NOT NULL, provider_user_id VARCHAR(255) NOT NULL, access_token TEXT DEFAULT NULL, refresh_token TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EAB41DB0A76ED395 ON oauth_accounts (user_id)');
        $this->addSql('CREATE TABLE payment_methods (provider VARCHAR(50) NOT NULL, provider_payment_method_id VARCHAR(255) NOT NULL, brand VARCHAR(50) DEFAULT NULL, last4 VARCHAR(4) DEFAULT NULL, expiration_month INT DEFAULT NULL, expiration_year INT DEFAULT NULL, id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4FABF983A76ED395 ON payment_methods (user_id)');
        $this->addSql('CREATE TABLE payments (provider VARCHAR(50) NOT NULL, provider_payment_intent VARCHAR(255) NOT NULL, amount NUMERIC(10, 2) NOT NULL, currency VARCHAR(10) NOT NULL, status VARCHAR(50) NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reservation_id UUID NOT NULL, payer_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65D29B32B83297E7 ON payments (reservation_id)');
        $this->addSql('CREATE INDEX IDX_65D29B32C17AD9A9 ON payments (payer_id)');
        $this->addSql('CREATE TABLE payouts (amount NUMERIC(10, 2) NOT NULL, currency VARCHAR(10) NOT NULL, status VARCHAR(50) NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id UUID NOT NULL, host_id UUID NOT NULL, reservation_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F54E808E1FB8D185 ON payouts (host_id)');
        $this->addSql('CREATE INDEX IDX_F54E808EB83297E7 ON payouts (reservation_id)');
        $this->addSql('CREATE TABLE properties (title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, property_type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, max_guests INT NOT NULL, bedrooms INT NOT NULL, beds INT NOT NULL, bathrooms INT NOT NULL, price_per_night NUMERIC(10, 2) NOT NULL, cleaning_fee NUMERIC(10, 2) DEFAULT NULL, security_deposit NUMERIC(10, 2) DEFAULT NULL, checkin_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, checkout_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, instant_booking BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id UUID NOT NULL, host_id UUID NOT NULL, cancellation_policy_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_87C331C71FB8D185 ON properties (host_id)');
        $this->addSql('CREATE INDEX IDX_87C331C7F0C13F52 ON properties (cancellation_policy_id)');
        $this->addSql('CREATE TABLE property_addresses (country VARCHAR(100) NOT NULL, city VARCHAR(100) NOT NULL, postal_code VARCHAR(20) DEFAULT NULL, address_line1 VARCHAR(255) NOT NULL, address_line2 VARCHAR(255) DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, id UUID NOT NULL, property_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E2577AB549213EC ON property_addresses (property_id)');
        $this->addSql('CREATE TABLE property_amenities (property_id UUID NOT NULL, amenity_id UUID NOT NULL, PRIMARY KEY (property_id, amenity_id))');
        $this->addSql('CREATE INDEX IDX_9A9F56CA549213EC ON property_amenities (property_id)');
        $this->addSql('CREATE INDEX IDX_9A9F56CA9F9F1305 ON property_amenities (amenity_id)');
        $this->addSql('CREATE TABLE property_availability (available_date DATE NOT NULL, is_available BOOLEAN NOT NULL, price_override NUMERIC(10, 2) DEFAULT NULL, minimum_stay INT DEFAULT NULL, id UUID NOT NULL, property_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F0B252E6549213EC ON property_availability (property_id)');
        $this->addSql('CREATE TABLE property_ical_sync (provider_name VARCHAR(100) NOT NULL, i_cal_url TEXT NOT NULL, last_sync_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id UUID NOT NULL, property_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DC997CB8549213EC ON property_ical_sync (property_id)');
        $this->addSql('CREATE TABLE property_media (media_type VARCHAR(50) NOT NULL, file_url TEXT NOT NULL, sort_order INT NOT NULL, is_cover BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, property_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC3F6001549213EC ON property_media (property_id)');
        $this->addSql('CREATE TABLE property_rules (pets_allowed BOOLEAN NOT NULL, smoking_allowed BOOLEAN NOT NULL, parties_allowed BOOLEAN NOT NULL, additional_rules TEXT DEFAULT NULL, id UUID NOT NULL, property_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4F895831549213EC ON property_rules (property_id)');
        $this->addSql('CREATE TABLE refunds (amount NUMERIC(10, 2) NOT NULL, reason TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, payment_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7EE53AD94C3A3BB ON refunds (payment_id)');
        $this->addSql('CREATE TABLE reports (target_type VARCHAR(50) NOT NULL, target UUID NOT NULL, reason TEXT NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reporter_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F11FA745E1CFE6F5 ON reports (reporter_id)');
        $this->addSql('CREATE TABLE reservation_status_history (old_status VARCHAR(50) DEFAULT NULL, new_status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reservation_id UUID NOT NULL, changed_by_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3A5E46F7B83297E7 ON reservation_status_history (reservation_id)');
        $this->addSql('CREATE INDEX IDX_3A5E46F7828AD0A0 ON reservation_status_history (changed_by_id)');
        $this->addSql('CREATE TABLE reservations (checkin_date DATE NOT NULL, checkout_date DATE NOT NULL, guests_count INT NOT NULL, status VARCHAR(50) NOT NULL, total_price NUMERIC(10, 2) NOT NULL, cleaning_fee NUMERIC(10, 2) DEFAULT NULL, service_fee NUMERIC(10, 2) DEFAULT NULL, security_deposit NUMERIC(10, 2) DEFAULT NULL, currency VARCHAR(10) NOT NULL, cancellation_reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, property_id UUID NOT NULL, guest_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4DA239549213EC ON reservations (property_id)');
        $this->addSql('CREATE INDEX IDX_4DA2399A4AA658 ON reservations (guest_id)');
        $this->addSql('CREATE TABLE review_media (file_url TEXT NOT NULL, id UUID NOT NULL, review_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_79A28D173E2E969B ON review_media (review_id)');
        $this->addSql('CREATE TABLE review_reports (reason TEXT NOT NULL, status VARCHAR(50) NOT NULL, id UUID NOT NULL, review_id UUID NOT NULL, reported_by_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6AF113B23E2E969B ON review_reports (review_id)');
        $this->addSql('CREATE INDEX IDX_6AF113B271CE806 ON review_reports (reported_by_id)');
        $this->addSql('CREATE TABLE reviews (rating INT NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, reservation_id UUID NOT NULL, reviewer_id UUID NOT NULL, reviewed_user_id UUID NOT NULL, property_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6970EB0FB83297E7 ON reviews (reservation_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0F70574616 ON reviews (reviewer_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0FB9A2A077 ON reviews (reviewed_user_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0F549213EC ON reviews (property_id)');
        $this->addSql('CREATE TABLE roles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B63E2EC777153098 ON roles (code)');
        $this->addSql('CREATE TABLE user_documents (type VARCHAR(50) NOT NULL, file_url TEXT NOT NULL, verification_status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A250FF6CA76ED395 ON user_documents (user_id)');
        $this->addSql('CREATE TABLE user_profiles (first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, birth_date DATE DEFAULT NULL, avatar_url TEXT DEFAULT NULL, bio TEXT DEFAULT NULL, identity_status VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6BBD6130A76ED395 ON user_profiles (user_id)');
        $this->addSql('CREATE TABLE user_roles (user_id UUID NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_54FCD59FA76ED395 ON user_roles (user_id)');
        $this->addSql('CREATE INDEX IDX_54FCD59FD60322AC ON user_roles (role_id)');
        $this->addSql('CREATE TABLE users (email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, phone VARCHAR(50) DEFAULT NULL, status VARCHAR(50) NOT NULL, is_email_verified BOOLEAN NOT NULL, is2fa_enabled BOOLEAN NOT NULL, preferred_language VARCHAR(10) DEFAULT NULL, preferred_currency VARCHAR(10) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_D62F2858A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation_participants ADD CONSTRAINT FK_21821ED39AC0396 FOREIGN KEY (conversation_id) REFERENCES conversations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation_participants ADD CONSTRAINT FK_21821ED3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversations ADD CONSTRAINT FK_C2521BF1B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE disputes ADD CONSTRAINT FK_8556C8F8B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE disputes ADD CONSTRAINT FK_8556C8F8AB159F5 FOREIGN KEY (opened_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoices ADD CONSTRAINT FK_6A2F2F95B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E969AC0396 FOREIGN KEY (conversation_id) REFERENCES conversations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96F624B39D FOREIGN KEY (sender_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE oauth_accounts ADD CONSTRAINT FK_EAB41DB0A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment_methods ADD CONSTRAINT FK_4FABF983A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B32B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B32C17AD9A9 FOREIGN KEY (payer_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payouts ADD CONSTRAINT FK_F54E808E1FB8D185 FOREIGN KEY (host_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payouts ADD CONSTRAINT FK_F54E808EB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE properties ADD CONSTRAINT FK_87C331C71FB8D185 FOREIGN KEY (host_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE properties ADD CONSTRAINT FK_87C331C7F0C13F52 FOREIGN KEY (cancellation_policy_id) REFERENCES cancellation_policies (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_addresses ADD CONSTRAINT FK_1E2577AB549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_amenities ADD CONSTRAINT FK_9A9F56CA549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_amenities ADD CONSTRAINT FK_9A9F56CA9F9F1305 FOREIGN KEY (amenity_id) REFERENCES amenities (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_availability ADD CONSTRAINT FK_F0B252E6549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_ical_sync ADD CONSTRAINT FK_DC997CB8549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_media ADD CONSTRAINT FK_AC3F6001549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_rules ADD CONSTRAINT FK_4F895831549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE refunds ADD CONSTRAINT FK_7EE53AD94C3A3BB FOREIGN KEY (payment_id) REFERENCES payments (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT FK_F11FA745E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation_status_history ADD CONSTRAINT FK_3A5E46F7B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation_status_history ADD CONSTRAINT FK_3A5E46F7828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA239549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA2399A4AA658 FOREIGN KEY (guest_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review_media ADD CONSTRAINT FK_79A28D173E2E969B FOREIGN KEY (review_id) REFERENCES reviews (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review_reports ADD CONSTRAINT FK_6AF113B23E2E969B FOREIGN KEY (review_id) REFERENCES reviews (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review_reports ADD CONSTRAINT FK_6AF113B271CE806 FOREIGN KEY (reported_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0F70574616 FOREIGN KEY (reviewer_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FB9A2A077 FOREIGN KEY (reviewed_user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0F549213EC FOREIGN KEY (property_id) REFERENCES properties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_documents ADD CONSTRAINT FK_A250FF6CA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_profiles ADD CONSTRAINT FK_6BBD6130A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FD60322AC FOREIGN KEY (role_id) REFERENCES roles (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE availability DROP CONSTRAINT fk_3fb7a2bf549213ec');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT fk_e00cedde549213ec');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT fk_e00cedde9a4aa658');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT fk_8a8e26e9b29a9963');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT fk_8a8e26e9a02f368d');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT fk_8a8e26e93301c60');
        $this->addSql('ALTER TABLE gamification_user_stats DROP CONSTRAINT fk_ef4374a6a76ed395');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT fk_b6bd307f9ac0396');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT fk_b6bd307ff624b39d');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT fk_6d28840d3301c60');
        $this->addSql('ALTER TABLE property DROP CONSTRAINT fk_8bf21cde1fb8d185');
        $this->addSql('ALTER TABLE property_amenity DROP CONSTRAINT fk_f2ad331b549213ec');
        $this->addSql('ALTER TABLE property_amenity DROP CONSTRAINT fk_f2ad331b9f9f1305');
        $this->addSql('ALTER TABLE property_photo DROP CONSTRAINT fk_d2a44515549213ec');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT fk_794381c63301c60');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT fk_794381c670574616');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT fk_794381c6bd992930');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT fk_1c32b345a76ed395');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT fk_1c32b345f7a2c2fc');
        $this->addSql('ALTER TABLE user_challenge DROP CONSTRAINT fk_d7e904b5a76ed395');
        $this->addSql('ALTER TABLE user_challenge DROP CONSTRAINT fk_d7e904b598a21ac6');
        $this->addSql('ALTER TABLE user_reward DROP CONSTRAINT fk_2b83696ea76ed395');
        $this->addSql('ALTER TABLE user_reward DROP CONSTRAINT fk_2b83696ee466aca1');
        $this->addSql('DROP TABLE amenity');
        $this->addSql('DROP TABLE availability');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE challenge');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE gamification_user_stats');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE property');
        $this->addSql('DROP TABLE property_amenity');
        $this->addSql('DROP TABLE property_photo');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE reward');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_badge');
        $this->addSql('DROP TABLE user_challenge');
        $this->addSql('DROP TABLE user_reward');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE amenity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, icon VARCHAR(100) DEFAULT NULL, category VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE availability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, is_available BOOLEAN NOT NULL, price_override NUMERIC(10, 2) DEFAULT NULL, property_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_3fb7a2bf549213ec ON availability (property_id)');
        $this->addSql('CREATE TABLE badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, icon_url VARCHAR(500) DEFAULT NULL, category VARCHAR(50) DEFAULT NULL, requirement_type VARCHAR(50) DEFAULT NULL, requirement_value INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, check_in_date DATE NOT NULL, check_out_date DATE NOT NULL, number_of_guests INT NOT NULL, total_price NUMERIC(10, 2) NOT NULL, commission_amount NUMERIC(10, 2) DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, property_id INT NOT NULL, guest_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_e00cedde549213ec ON booking (property_id)');
        $this->addSql('CREATE INDEX idx_e00cedde9a4aa658 ON booking (guest_id)');
        $this->addSql('CREATE TABLE challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, challenge_type VARCHAR(50) DEFAULT NULL, target_value INT DEFAULT NULL, points_reward INT DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_message_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, participant1_id INT NOT NULL, participant2_id INT NOT NULL, booking_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_8a8e26e93301c60 ON conversation (booking_id)');
        $this->addSql('CREATE INDEX idx_8a8e26e9b29a9963 ON conversation (participant1_id)');
        $this->addSql('CREATE INDEX idx_8a8e26e9a02f368d ON conversation (participant2_id)');
        $this->addSql('CREATE TABLE gamification_user_stats (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_points INT NOT NULL, level INT NOT NULL, bookings_count INT NOT NULL, reviews_count INT NOT NULL, countries_visited INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_ef4374a6a76ed395 ON gamification_user_stats (user_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, is_read BOOLEAN NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conversation_id INT NOT NULL, sender_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_b6bd307f9ac0396 ON message (conversation_id)');
        $this->addSql('CREATE INDEX idx_b6bd307ff624b39d ON message (sender_id)');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, currency VARCHAR(3) NOT NULL, payment_method VARCHAR(50) DEFAULT NULL, status VARCHAR(20) NOT NULL, transaction_id VARCHAR(255) DEFAULT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, released_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, booking_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_6d28840d3301c60 ON payment (booking_id)');
        $this->addSql('CREATE TABLE property (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, property_type VARCHAR(50) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, country VARCHAR(100) DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, latitude NUMERIC(10, 8) DEFAULT NULL, longitude NUMERIC(11, 8) DEFAULT NULL, max_guests INT DEFAULT NULL, bedrooms INT DEFAULT NULL, beds INT DEFAULT NULL, bathrooms NUMERIC(3, 1) DEFAULT NULL, price_per_night NUMERIC(10, 2) DEFAULT NULL, cleaning_fee NUMERIC(10, 2) DEFAULT NULL, status VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, host_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_8bf21cde1fb8d185 ON property (host_id)');
        $this->addSql('CREATE TABLE property_amenity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, property_id INT NOT NULL, amenity_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_f2ad331b9f9f1305 ON property_amenity (amenity_id)');
        $this->addSql('CREATE INDEX idx_f2ad331b549213ec ON property_amenity (property_id)');
        $this->addSql('CREATE TABLE property_photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, photo_url VARCHAR(500) NOT NULL, display_order INT DEFAULT NULL, is_cover BOOLEAN NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, property_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d2a44515549213ec ON property_photo (property_id)');
        $this->addSql('CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating INT NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, booking_id INT NOT NULL, reviewer_id INT NOT NULL, reviewee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_794381c670574616 ON review (reviewer_id)');
        $this->addSql('CREATE INDEX idx_794381c63301c60 ON review (booking_id)');
        $this->addSql('CREATE INDEX idx_794381c6bd992930 ON review (reviewee_id)');
        $this->addSql('CREATE TABLE reward (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, reward_type VARCHAR(50) DEFAULT NULL, discount_percentage NUMERIC(5, 2) DEFAULT NULL, discount_amount NUMERIC(10, 2) DEFAULT NULL, points_required INT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, profile_picture_url VARCHAR(500) DEFAULT NULL, bio TEXT DEFAULT NULL, language VARCHAR(10) DEFAULT NULL, currency VARCHAR(3) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_8d93d649e7927c74 ON "user" (email)');
        $this->addSql('CREATE TABLE user_badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, earned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, badge_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_1c32b345a76ed395 ON user_badge (user_id)');
        $this->addSql('CREATE INDEX idx_1c32b345f7a2c2fc ON user_badge (badge_id)');
        $this->addSql('CREATE TABLE user_challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, current_progress INT NOT NULL, is_completed BOOLEAN NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, challenge_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d7e904b5a76ed395 ON user_challenge (user_id)');
        $this->addSql('CREATE INDEX idx_d7e904b598a21ac6 ON user_challenge (challenge_id)');
        $this->addSql('CREATE TABLE user_reward (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, redeemed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, earned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, reward_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_2b83696ea76ed395 ON user_reward (user_id)');
        $this->addSql('CREATE INDEX idx_2b83696ee466aca1 ON user_reward (reward_id)');
        $this->addSql('ALTER TABLE availability ADD CONSTRAINT fk_3fb7a2bf549213ec FOREIGN KEY (property_id) REFERENCES property (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT fk_e00cedde549213ec FOREIGN KEY (property_id) REFERENCES property (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT fk_e00cedde9a4aa658 FOREIGN KEY (guest_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT fk_8a8e26e9b29a9963 FOREIGN KEY (participant1_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT fk_8a8e26e9a02f368d FOREIGN KEY (participant2_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT fk_8a8e26e93301c60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gamification_user_stats ADD CONSTRAINT fk_ef4374a6a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT fk_b6bd307f9ac0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT fk_b6bd307ff624b39d FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT fk_6d28840d3301c60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE property ADD CONSTRAINT fk_8bf21cde1fb8d185 FOREIGN KEY (host_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE property_amenity ADD CONSTRAINT fk_f2ad331b549213ec FOREIGN KEY (property_id) REFERENCES property (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE property_amenity ADD CONSTRAINT fk_f2ad331b9f9f1305 FOREIGN KEY (amenity_id) REFERENCES amenity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE property_photo ADD CONSTRAINT fk_d2a44515549213ec FOREIGN KEY (property_id) REFERENCES property (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT fk_794381c63301c60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT fk_794381c670574616 FOREIGN KEY (reviewer_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT fk_794381c6bd992930 FOREIGN KEY (reviewee_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT fk_1c32b345a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT fk_1c32b345f7a2c2fc FOREIGN KEY (badge_id) REFERENCES badge (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_challenge ADD CONSTRAINT fk_d7e904b5a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_challenge ADD CONSTRAINT fk_d7e904b598a21ac6 FOREIGN KEY (challenge_id) REFERENCES challenge (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_reward ADD CONSTRAINT fk_2b83696ea76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_reward ADD CONSTRAINT fk_2b83696ee466aca1 FOREIGN KEY (reward_id) REFERENCES reward (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT FK_D62F2858A76ED395');
        $this->addSql('ALTER TABLE conversation_participants DROP CONSTRAINT FK_21821ED39AC0396');
        $this->addSql('ALTER TABLE conversation_participants DROP CONSTRAINT FK_21821ED3A76ED395');
        $this->addSql('ALTER TABLE conversations DROP CONSTRAINT FK_C2521BF1B83297E7');
        $this->addSql('ALTER TABLE disputes DROP CONSTRAINT FK_8556C8F8B83297E7');
        $this->addSql('ALTER TABLE disputes DROP CONSTRAINT FK_8556C8F8AB159F5');
        $this->addSql('ALTER TABLE invoices DROP CONSTRAINT FK_6A2F2F95B83297E7');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E969AC0396');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96F624B39D');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE oauth_accounts DROP CONSTRAINT FK_EAB41DB0A76ED395');
        $this->addSql('ALTER TABLE payment_methods DROP CONSTRAINT FK_4FABF983A76ED395');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B32B83297E7');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B32C17AD9A9');
        $this->addSql('ALTER TABLE payouts DROP CONSTRAINT FK_F54E808E1FB8D185');
        $this->addSql('ALTER TABLE payouts DROP CONSTRAINT FK_F54E808EB83297E7');
        $this->addSql('ALTER TABLE properties DROP CONSTRAINT FK_87C331C71FB8D185');
        $this->addSql('ALTER TABLE properties DROP CONSTRAINT FK_87C331C7F0C13F52');
        $this->addSql('ALTER TABLE property_addresses DROP CONSTRAINT FK_1E2577AB549213EC');
        $this->addSql('ALTER TABLE property_amenities DROP CONSTRAINT FK_9A9F56CA549213EC');
        $this->addSql('ALTER TABLE property_amenities DROP CONSTRAINT FK_9A9F56CA9F9F1305');
        $this->addSql('ALTER TABLE property_availability DROP CONSTRAINT FK_F0B252E6549213EC');
        $this->addSql('ALTER TABLE property_ical_sync DROP CONSTRAINT FK_DC997CB8549213EC');
        $this->addSql('ALTER TABLE property_media DROP CONSTRAINT FK_AC3F6001549213EC');
        $this->addSql('ALTER TABLE property_rules DROP CONSTRAINT FK_4F895831549213EC');
        $this->addSql('ALTER TABLE refunds DROP CONSTRAINT FK_7EE53AD94C3A3BB');
        $this->addSql('ALTER TABLE reports DROP CONSTRAINT FK_F11FA745E1CFE6F5');
        $this->addSql('ALTER TABLE reservation_status_history DROP CONSTRAINT FK_3A5E46F7B83297E7');
        $this->addSql('ALTER TABLE reservation_status_history DROP CONSTRAINT FK_3A5E46F7828AD0A0');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT FK_4DA239549213EC');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT FK_4DA2399A4AA658');
        $this->addSql('ALTER TABLE review_media DROP CONSTRAINT FK_79A28D173E2E969B');
        $this->addSql('ALTER TABLE review_reports DROP CONSTRAINT FK_6AF113B23E2E969B');
        $this->addSql('ALTER TABLE review_reports DROP CONSTRAINT FK_6AF113B271CE806');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0FB83297E7');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0F70574616');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0FB9A2A077');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0F549213EC');
        $this->addSql('ALTER TABLE user_documents DROP CONSTRAINT FK_A250FF6CA76ED395');
        $this->addSql('ALTER TABLE user_profiles DROP CONSTRAINT FK_6BBD6130A76ED395');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FA76ED395');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FD60322AC');
        $this->addSql('DROP TABLE amenities');
        $this->addSql('DROP TABLE audit_logs');
        $this->addSql('DROP TABLE cancellation_policies');
        $this->addSql('DROP TABLE conversation_participants');
        $this->addSql('DROP TABLE conversations');
        $this->addSql('DROP TABLE disputes');
        $this->addSql('DROP TABLE invoices');
        $this->addSql('DROP TABLE messages');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE oauth_accounts');
        $this->addSql('DROP TABLE payment_methods');
        $this->addSql('DROP TABLE payments');
        $this->addSql('DROP TABLE payouts');
        $this->addSql('DROP TABLE properties');
        $this->addSql('DROP TABLE property_addresses');
        $this->addSql('DROP TABLE property_amenities');
        $this->addSql('DROP TABLE property_availability');
        $this->addSql('DROP TABLE property_ical_sync');
        $this->addSql('DROP TABLE property_media');
        $this->addSql('DROP TABLE property_rules');
        $this->addSql('DROP TABLE refunds');
        $this->addSql('DROP TABLE reports');
        $this->addSql('DROP TABLE reservation_status_history');
        $this->addSql('DROP TABLE reservations');
        $this->addSql('DROP TABLE review_media');
        $this->addSql('DROP TABLE review_reports');
        $this->addSql('DROP TABLE reviews');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE user_documents');
        $this->addSql('DROP TABLE user_profiles');
        $this->addSql('DROP TABLE user_roles');
        $this->addSql('DROP TABLE users');
    }
}
