<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260610164051 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        if ($schema->hasTable('user_roles')) {
            $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT IF EXISTS fk_54fcd59fa76ed395');
            $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT IF EXISTS fk_54fcd59fd60322ac');
            $this->addSql('DROP TABLE user_roles');
        }

        if ($schema->hasTable('roles')) {
            $this->addSql('DROP TABLE roles');
        }

        if (!$schema->getTable('users')->hasColumn('roles')) {
            $this->addSql("ALTER TABLE users ADD roles JSON NOT NULL DEFAULT '[]'");
        }
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE roles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_b63e2ec777153098 ON roles (code)');
        $this->addSql('CREATE TABLE user_roles (user_id UUID NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('CREATE INDEX idx_54fcd59fd60322ac ON user_roles (role_id)');
        $this->addSql('CREATE INDEX idx_54fcd59fa76ed395 ON user_roles (user_id)');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT fk_54fcd59fa76ed395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT fk_54fcd59fd60322ac FOREIGN KEY (role_id) REFERENCES roles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users DROP roles');
    }
}
