<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260609103246 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin_action (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action_type VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, target_type VARCHAR(100) DEFAULT NULL, target_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, admin_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1A04BD6B642B8210 ON admin_action (admin_id)');
        $this->addSql('CREATE TABLE amenity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, icon VARCHAR(255) DEFAULT NULL, category VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cancellation_policy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, refund_rules_json JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, listing_id INT NOT NULL, booking_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A8E26E9D4619D1A ON conversation (listing_id)');
        $this->addSql('CREATE INDEX IDX_8A8E26E93301C60 ON conversation (booking_id)');
        $this->addSql('CREATE TABLE conversation_participants (conversation_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (conversation_id, user_id))');
        $this->addSql('CREATE INDEX IDX_21821ED39AC0396 ON conversation_participants (conversation_id)');
        $this->addSql('CREATE INDEX IDX_21821ED3A76ED395 ON conversation_participants (user_id)');
        $this->addSql('CREATE TABLE dispute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reason TEXT NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, resolution TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, booking_id INT NOT NULL, raised_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3C9250073301C60 ON dispute (booking_id)');
        $this->addSql('CREATE INDEX IDX_3C925007B0CDEB44 ON dispute (raised_by_id)');
        $this->addSql('CREATE TABLE listing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, price_per_night NUMERIC(10, 2) NOT NULL, max_guests INT NOT NULL, bedrooms INT NOT NULL, bathrooms NUMERIC(3, 1) NOT NULL, property_type VARCHAR(100) NOT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, city VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, host_id INT NOT NULL, cancellation_policy_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CB0048D41FB8D185 ON listing (host_id)');
        $this->addSql('CREATE INDEX IDX_CB0048D4F0C13F52 ON listing (cancellation_policy_id)');
        $this->addSql('CREATE TABLE listing_amenities (listing_id INT NOT NULL, amenity_id INT NOT NULL, PRIMARY KEY (listing_id, amenity_id))');
        $this->addSql('CREATE INDEX IDX_5B46B037D4619D1A ON listing_amenities (listing_id)');
        $this->addSql('CREATE INDEX IDX_5B46B0379F9F1305 ON listing_amenities (amenity_id)');
        $this->addSql('CREATE TABLE listing_photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, listing_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E2595C94D4619D1A ON listing_photo (listing_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conversation_id INT NOT NULL, sender_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F9AC0396 ON message (conversation_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FF624B39D ON message (sender_id)');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, currency VARCHAR(10) NOT NULL, payment_method VARCHAR(100) NOT NULL, status VARCHAR(50) NOT NULL, platform_fee NUMERIC(10, 2) NOT NULL, host_amount NUMERIC(10, 2) NOT NULL, transaction_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, booking_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6D28840D3301C60 ON payment (booking_id)');
        $this->addSql('CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating INT NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, booking_id INT NOT NULL, reviewer_id INT NOT NULL, reviewee_id INT NOT NULL, listing_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_794381C63301C60 ON review (booking_id)');
        $this->addSql('CREATE INDEX IDX_794381C670574616 ON review (reviewer_id)');
        $this->addSql('CREATE INDEX IDX_794381C6BD992930 ON review (reviewee_id)');
        $this->addSql('CREATE INDEX IDX_794381C6D4619D1A ON review (listing_id)');
        $this->addSql('ALTER TABLE admin_action ADD CONSTRAINT FK_1A04BD6B642B8210 FOREIGN KEY (admin_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E93301C60 FOREIGN KEY (booking_id) REFERENCES booking (id)');
        $this->addSql('ALTER TABLE conversation_participants ADD CONSTRAINT FK_21821ED39AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conversation_participants ADD CONSTRAINT FK_21821ED3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dispute ADD CONSTRAINT FK_3C9250073301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dispute ADD CONSTRAINT FK_3C925007B0CDEB44 FOREIGN KEY (raised_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE listing ADD CONSTRAINT FK_CB0048D41FB8D185 FOREIGN KEY (host_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE listing ADD CONSTRAINT FK_CB0048D4F0C13F52 FOREIGN KEY (cancellation_policy_id) REFERENCES cancellation_policy (id)');
        $this->addSql('ALTER TABLE listing_amenities ADD CONSTRAINT FK_5B46B037D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE listing_amenities ADD CONSTRAINT FK_5B46B0379F9F1305 FOREIGN KEY (amenity_id) REFERENCES amenity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE listing_photo ADD CONSTRAINT FK_E2595C94D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D3301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C63301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C670574616 FOREIGN KEY (reviewer_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6BD992930 FOREIGN KEY (reviewee_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD status VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE booking ADD special_requests TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE booking ADD listing_id INT NOT NULL');
        $this->addSql('ALTER TABLE booking ALTER total_price TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER TABLE booking ALTER currency TYPE VARCHAR(10)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDED4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_E00CEDDED4619D1A ON booking (listing_id)');
        $this->addSql('ALTER TABLE notification ADD user_id INT NOT NULL');
        $this->addSql('ALTER TABLE notification ALTER type TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('ALTER TABLE "user" ADD role VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER email TYPE VARCHAR(180)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('ALTER TABLE user_profile ADD language VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE user_profile ADD user_id INT NOT NULL');
        $this->addSql('ALTER TABLE user_profile DROP languague');
        $this->addSql('ALTER TABLE user_profile ALTER phone DROP NOT NULL');
        $this->addSql('ALTER TABLE user_profile ALTER country DROP NOT NULL');
        $this->addSql('ALTER TABLE user_profile ADD CONSTRAINT FK_D95AB405A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D95AB405A76ED395 ON user_profile (user_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admin_action DROP CONSTRAINT FK_1A04BD6B642B8210');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9D4619D1A');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E93301C60');
        $this->addSql('ALTER TABLE conversation_participants DROP CONSTRAINT FK_21821ED39AC0396');
        $this->addSql('ALTER TABLE conversation_participants DROP CONSTRAINT FK_21821ED3A76ED395');
        $this->addSql('ALTER TABLE dispute DROP CONSTRAINT FK_3C9250073301C60');
        $this->addSql('ALTER TABLE dispute DROP CONSTRAINT FK_3C925007B0CDEB44');
        $this->addSql('ALTER TABLE listing DROP CONSTRAINT FK_CB0048D41FB8D185');
        $this->addSql('ALTER TABLE listing DROP CONSTRAINT FK_CB0048D4F0C13F52');
        $this->addSql('ALTER TABLE listing_amenities DROP CONSTRAINT FK_5B46B037D4619D1A');
        $this->addSql('ALTER TABLE listing_amenities DROP CONSTRAINT FK_5B46B0379F9F1305');
        $this->addSql('ALTER TABLE listing_photo DROP CONSTRAINT FK_E2595C94D4619D1A');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F9AC0396');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D3301C60');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C63301C60');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C670574616');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6BD992930');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6D4619D1A');
        $this->addSql('DROP TABLE admin_action');
        $this->addSql('DROP TABLE amenity');
        $this->addSql('DROP TABLE cancellation_policy');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE conversation_participants');
        $this->addSql('DROP TABLE dispute');
        $this->addSql('DROP TABLE listing');
        $this->addSql('DROP TABLE listing_amenities');
        $this->addSql('DROP TABLE listing_photo');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE review');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDED4619D1A');
        $this->addSql('DROP INDEX IDX_E00CEDDED4619D1A');
        $this->addSql('ALTER TABLE booking DROP status');
        $this->addSql('ALTER TABLE booking DROP special_requests');
        $this->addSql('ALTER TABLE booking DROP listing_id');
        $this->addSql('ALTER TABLE booking ALTER total_price TYPE NUMERIC(5, 2)');
        $this->addSql('ALTER TABLE booking ALTER currency TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('DROP INDEX IDX_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE notification DROP user_id');
        $this->addSql('ALTER TABLE notification ALTER type TYPE VARCHAR(255)');
        $this->addSql('DROP INDEX UNIQ_8D93D649E7927C74');
        $this->addSql('ALTER TABLE "user" DROP role');
        $this->addSql('ALTER TABLE "user" ALTER email TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE user_profile DROP CONSTRAINT FK_D95AB405A76ED395');
        $this->addSql('DROP INDEX UNIQ_D95AB405A76ED395');
        $this->addSql('ALTER TABLE user_profile ADD languague VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE user_profile DROP language');
        $this->addSql('ALTER TABLE user_profile DROP user_id');
        $this->addSql('ALTER TABLE user_profile ALTER phone SET NOT NULL');
        $this->addSql('ALTER TABLE user_profile ALTER country SET NOT NULL');
    }
}
