<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260611102533 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE blocked_period (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, reason VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, listing_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7104E1B8D4619D1A ON blocked_period (listing_id)');
        $this->addSql('ALTER TABLE blocked_period ADD CONSTRAINT FK_7104E1B8D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD cancel_reason TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE listing ADD instant_booking BOOLEAN NOT NULL DEFAULT FALSE');
        $this->addSql('ALTER TABLE listing ADD ical_token VARCHAR(64) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CB0048D49F0C901D ON listing (ical_token)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE blocked_period DROP CONSTRAINT FK_7104E1B8D4619D1A');
        $this->addSql('DROP TABLE blocked_period');
        $this->addSql('ALTER TABLE booking DROP cancel_reason');
        $this->addSql('DROP INDEX UNIQ_CB0048D49F0C901D');
        $this->addSql('ALTER TABLE listing DROP instant_booking');
        $this->addSql('ALTER TABLE listing DROP ical_token');
    }
}
